language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
env:
  - NODE_ENV=test
install:
  - npm install -g codecov
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec
  - codecov