language: node_js
node_js:
  - "4.1"
  - "4.0"
  - "0.12"
env:
  - NODE_ENV=test
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha -- -R spec \
  && cat ./coverage/coverage.json | ./node_modules/codecov.io/bin/codecov.io.js